// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAQNsJkMThAZcYtZEuzuZvoh9YBWDKu1A',
    appId: '1:546220032524:android:4b6822fd72f81703d02429',
    messagingSenderId: '546220032524',
    projectId: 'medicine-3d45f',
    databaseURL: 'https://medicine-3d45f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medicine-3d45f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn3NuJL7LQrkbBliSkdNp5FQcab1YR_Gs',
    appId: '1:546220032524:ios:fe813f23399f7999d02429',
    messagingSenderId: '546220032524',
    projectId: 'medicine-3d45f',
    databaseURL: 'https://medicine-3d45f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medicine-3d45f.appspot.com',
    iosClientId: '546220032524-ve3huqpk8r4vgq8gjbrh3n99tpl2astt.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicine',
  );
}
